// <auto-generated />
using CRAC.Api.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRAC.Api.Migrations
{
    [DbContext(typeof(CracContext))]
    [Migration("20190611031722_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("CRAC.Api.SQLite.Moviment", b =>
                {
                    b.Property<int>("MovimentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Base");

                    b.Property<int>("Claw");

                    b.Property<int>("Left");

                    b.Property<int>("Right");

                    b.HasKey("MovimentId");

                    b.ToTable("Moviments");
                });
#pragma warning restore 612, 618
        }
    }
}
